# Generated by Django 4.2.6 on 2024-01-23 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="friends",
        ),
    ]
